### ISSUE TITLE
Locally optimal solutions

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/network#3]
The example in commit b2d7293 shows that we are getting locally optimal solutions. Why, we must dig.

**Comment by 1ozturkbe** [comment]
Initializing the network flow GP with the LP solution returns a 10006 error per [Mosek](https://docs.mosek.com/8.1/capi/response-codes.html). This may be akin to the very close but not optimal solutions that SPaircraft would converge to.

**Comment by 1ozturkbe** [comment]
Initializing the network with a slightly greater than optimal solution (flow = flow+0.1) results in hitting iteration limits (tested 200). Reducing the epsilon and reltol also results in 10006 error.

**Comment by 1ozturkbe** [comment]
This has been resolved as of commit 1bc2440a88f, with the introduction of a slack variable to the LHS of the flow inequality at every node (fyi @alisaab). By penalizing the slack, we can traverse infeasible regions of the design space and get to the best solution! Closing.

**Comment by bqpd** [comment]
Awesome!

**Comment by alisaab** [comment]
smart move !! the LP solution is not the same as the SP though, right ?

**Comment by 1ozturkbe** [comment]
It is the same now! Does require occasional tuning, so needs more robustness.

**Comment by 1ozturkbe** [comment]
As a further note, multiplicative slack on LHS works, but additive (for some odd reason) doesn't. This likely has to do with the GP approximation.

**Comment by bqpd** [comment]
additive slack tends to be much more numerically challenged in gp, yeah.
I'd love to see an exploration of this, right now it's just modeler's
intuition.

**Comment by 1ozturkbe** [comment]
Pending work on DARPA stuff, yes I would like to see a greater exploration of this as well. But for now it works :P

**Comment by bqpd** [comment]
Oh sorry that wasn't a request! Just daydreaming
